export type Doctor = {
  id: string;
  email: string;
  name: string;
  avatar: string;
  practisingCertificate: string;
  certificateCode: string;
  placeOfCertificate: string;
  dateOfCertificate: string;
  scopeOfPractice: string;
  description: string;
  numberOfConsultants: string;
  numberOfCancels: string;
  rating: string;
  isVerify: true;
  isActive: true;
  certificationDoctors: any;
  hospitalDoctors: any;
  majorDoctors: any;
};
